server:
  port: 8081

spring:
  application:
    name: spring-boot-import-csv
  datasource:
    url: jdbc:postgresql://localhost:5432/import-csv
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
